---
  - name: Launch EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: false
    user: root
    pre_tasks:
    - include_vars: vars.yml
    roles:
    - provision-ec2

  - name: Setup Haystack Stack
    hosts: etl_hosts
    gather_facts: True
    user: ubuntu
    sudo: yes
    roles:
    - haystack_setup

  - name: Run Haystack
    hosts: etl_hosts
    gather_facts: True
    user: ubuntu
    vars:
      terms_uri: http://hub-client.lib.umn.edu/lookups/13.json
    sudo: no
    - haystack_run