---
  - name: Launch EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: false
    user: root
    roles:
    - provision-ec2
    vars:
      ec2_keypair: "mdletl"
      ec2_instance_type: "m4.10xlarge"
      ec2_security_group: "haystack"
      ec2_image: "ami-fce3c696"
      ec2_region: "us-east-1"
      ec2_tag_Name: "Haystack"
      ec2_tag_Type: "Haystack"
      ec2_tag_Environment: "production"
      ec2_volume_size: 150

  - name: Setup Haystack Stack
    hosts: etl_hosts
    gather_facts: True
    user: ubuntu
    sudo: yes
    roles:
    - haystack_setup

  - name: Run Haystack
    hosts: etl_hosts
    gather_facts: True
    user: ubuntu
    vars:
      terms_uri: http://hub-client.lib.umn.edu/lookups/1.json
      number_of_lines_per_chunk: 300000
    sudo: no
    roles:
    - haystack_run